development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://ozncetwrsaailv:56bbf6cc45fe72d12f74711a06d98236a497632158ca60eddda6cb70af917262@ec2-107-20-237-78.compute-1.amazonaws.com:5432/d43smgepd5q5ce
  channel_prefix: pragueyogacollective_production
